### ISSUE TITLE
Costo de viaje

### ISSUE THREAD

**Issue by crisnicogonzalez** [agufiuba/t2-android#6]
Cuando se solicita toda la información de un viaje, se muestra mal.

**Comment by Arkenan** [comment]
Esto estaría siendo un problema del appserver, que devuelve cosas del estilo: 

```
{
  'distance': '10.3 km', 
  'time': '21 mins', 
  'points': '[...]', 
  'cost': {'costo': 104.5}
}
```

donde tiempo y distancia tienen valores literales y el costo no.

**Comment by Arkenan** [comment]
Arreglado por Cristian en agufiuba/t2-app-server@c59663145a899eaf81eab605014450eb0f329c65.
